# Version of buildspec.yml
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # install npm, angular, and dependencies
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      # run build
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    # we need to use quotes to escape the asterisks because asterisk is a special character in YAML.
    - '**/*'
